import   typescript    from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import   commonjs      from "@rollup/plugin-commonjs";
import   terser        from "@rollup/plugin-terser";
import   dts           from "rollup-plugin-dts";

const isProd = ( process.env.BUILD === "production" );

const banner = 
`/*
 *  THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
 *  If you want to view the source, visit the plugins github repository
 */
`;

export default [
  {
    input: "src/lib/index.ts",
    output: {
      file: "index.js",
      format: "es",
      sourcemap: "inline",
      sourcemapExcludeSources: isProd,
      banner,
    },
    external: [ "obsidian" ],
    plugins: [
      typescript({
        tsconfig: ".config/tsconfig.build.json",
        declaration: false,
        declarationMap: false,
        outDir: undefined      // remove conflicting output dir/file
      }),
      nodeResolve({browser: true}),
      commonjs(),
      // Remove all remaining comments
      isProd && terser({
        compress: false, // no code obfuscation (compression)
        mangle: false,   // no code obfuscation (mangling)
        format: {
          comments: false, // remove comments
          beautify: true   // sorgt für ordentlich formatierten, mehrzeiligen Code
        }
      })
    ]
  },
  {
    input: "src/lib/index.ts",
    output: { 
      file: "index.d.ts", 
      format: "es" 
    },
    plugins: [dts()],
    external: ["obsidian"]
  }
];